In [52]:
#import libraries
import pandas as pd
import numpy as np

In [53]:
heart_disease = pd.read_csv('heart-disease.csv')

scikit work flow
1. get the data ready

In [54]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [55]:
X = heart_disease.drop("target", axis=1)

In [56]:
y = heart_disease["target"]

In [57]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [58]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [59]:
y.value_counts()

1    165
0    138
Name: target, dtype: int64

In [60]:
len(y)

303

splitting the model


In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [63]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

2. choose the right estimator


In [64]:
#since we are working on a classificatiopn problem, we will work with a random forest classifier
from sklearn.ensemble import RandomForestClassifier

In [65]:
#enstantiate the model
clf = RandomForestClassifier()

In [66]:
#view the current parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

3. fit the model and  use it to make prediction

In [67]:
clf.fit (X=X_train, y=y_train)

RandomForestClassifier()

In [68]:
# in order to make prediction on the label data, it has to be on the same shape.
X_train.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
41    48    1   1       130   245    0        0      180      0      0.2   
163   38    1   2       138   175    0        1      173      0      0.0   
176   60    1   0       117   230    1        1      160      1      1.4   
201   60    1   0       125   258    0        0      141      1      2.8   
82    60    0   2       102   318    0        1      160      0      0.0   

     slope  ca  thal  
41       1   0     2  
163      2   4     2  
176      2   2     3  
201      1   1     3  
82       2   1     2

In [69]:
#use the model to make predicition on the test data set
y_preds = clf.predict(X=X_test)


Evaluate the model

In [70]:
#evaluate the model on the train dataset
train_acc = clf.score (X=X_train, y=y_train)
print(f"The model's accuracy on the train dataset is : {train_acc*100}%")

The model's accuracy on the train dataset is : 100.0%


In [71]:
#this is 100% accurate because it has seen the train dataset

In [72]:
#evaluate the model on the test dataset
test_acc = clf.score (X=X_test, y=y_test)
print(f"The model's accuracy on the train dataset is : {test_acc*100:.2f}%")

The model's accuracy on the train dataset is : 77.05%


In [73]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [74]:
#create a classifictaion report
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.69      0.75      0.72        24
           1       0.83      0.78      0.81        37

    accuracy                           0.77        61
   macro avg       0.76      0.77      0.76        61
weighted avg       0.77      0.77      0.77        61



In [75]:
#create confusin matrix
conf_mat = confusion_matrix(y_preds, y_test )
conf_mat

array([[18,  8],
       [ 6, 29]], dtype=int64)

In [76]:
# create accuracy score
accuracy_score (y_preds, y_test)

0.7704918032786885

In [77]:
#note that RandomForestClassifier has 100 estimators by default, try another number of estimators
#try different numbers of estimators (no cross validation)
np.random.seed(42)

for i in range(100,200,10):
  print(f"trying model with {i} estimators...")
  model = RandomForestClassifier (n_estimators = i). fit(X_train, y_train)
  print (f"model accuracy on test set: {model.score(X_test, y_test)*100:.2f}%")
  print ("")

trying model with 100 estimators...
model accuracy on test set: 81.97%

trying model with 110 estimators...
model accuracy on test set: 78.69%

trying model with 120 estimators...
model accuracy on test set: 78.69%

trying model with 130 estimators...
model accuracy on test set: 78.69%

trying model with 140 estimators...
model accuracy on test set: 77.05%

trying model with 150 estimators...
model accuracy on test set: 77.05%

trying model with 160 estimators...
model accuracy on test set: 80.33%

trying model with 170 estimators...
model accuracy on test set: 75.41%

trying model with 180 estimators...
model accuracy on test set: 78.69%

trying model with 190 estimators...
model accuracy on test set: 78.69%



using cross validaton method

In [78]:
from sklearn.model_selection import cross_val_score

In [79]:
# with cross validation
np.random.seed(42)

for i in range(100,200,10):
  print(f"trying model with {i} estimators...")
  model = RandomForestClassifier (n_estimators = i). fit(X_train, y_train)
  print (f"model accuracy on test set: {model.score(X_test, y_test)*100:.2f}%")

  #measure the model score on a single train split
  modal_score = model.score(X_test, y_test)
  print (f"model accuracy on single test set split: {model.score(X_test, y_test)*100:.2f}%")


trying model with 100 estimators...
model accuracy on test set: 81.97%
model accuracy on single test set split: 81.97%
trying model with 110 estimators...
model accuracy on test set: 78.69%
model accuracy on single test set split: 78.69%
trying model with 120 estimators...
model accuracy on test set: 78.69%
model accuracy on single test set split: 78.69%
trying model with 130 estimators...
model accuracy on test set: 78.69%
model accuracy on single test set split: 78.69%
trying model with 140 estimators...
model accuracy on test set: 77.05%
model accuracy on single test set split: 77.05%
trying model with 150 estimators...
model accuracy on test set: 77.05%
model accuracy on single test set split: 77.05%
trying model with 160 estimators...
model accuracy on test set: 80.33%
model accuracy on single test set split: 80.33%
trying model with 170 estimators...
model accuracy on test set: 75.41%
model accuracy on single test set split: 75.41%
trying model with 180 estimators...
model accura

In [80]:
#measure the mean cross validation score across 5 different train test and split
cross_val_mean = np.mean(cross_val_score(model, X,y, cv=5))
print(f"5-fold cross-valaidation score:{cross_val_mean*100:.2f}%")
print("")


5-fold cross-valaidation score:81.82%



In [81]:
#another way to do it with GridsearchCv
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

In [82]:
#define the parameters to search over a dicitionary
# (these can any of your traget model's hyperparameter)
param_grid = {'n_estimators': [ i for i in range (100,200,10)]}

In [83]:
# set up the grid search
grid = GridSearchCV(estimator=RandomForestClassifier(), param_grid=param_grid, cv=5, verbose=1)

In [84]:
#fit the grid search to the data
grid.fit(X,y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [100, 110, 120, 130, 140, 150, 160,
                                          170, 180, 190]},
             verbose=1)

In [85]:
#find the best parameter
print (f"The best Parameter values are: {grid.best_params_}")
print (f"with a score of : {grid.best_score_*100:.2f}%")

The best Parameter values are: {'n_estimators': 120}
with a score of : 82.82%


In [86]:
# we can extract  the best model with the "best_estimator_" attriubte
#set the model to be the best estimator
clf = grid.best_estimator_
clf

RandomForestClassifier(n_estimators=120)

In [87]:
# And now we have got the best cross-validation model,
# we can fitr and score it on our original single train/test spilt of the data
# fit the best model
clf = clf.fit(X_train, y_train)

In [88]:
# find the best model score on our single test spilt
#(note: this may be lower than the cross-validation score, it's only on one splilt on the data)

print(f"Best model score on single split of the data: {clf.score(X_test, y_test)*100:.2f}%")

Best model score on single split of the data: 80.33%


save the model for use

In [89]:
# joblib is used for heavy dataset, while pickle is used for light data
import pickle

In [90]:
# save an existing model to file
pickle.dump(model, open("random_forest_model_1.pkl", "wb"))


In [91]:
# for large model, it may be more efficient to use joblib
from joblib import dump, load

In [92]:
# save a model using joblib
dump(model, "random_forest_model_1.joblib")

['random_forest_model_1.joblib']

In [93]:
#load a save pickle model and evaluate
loaded_pickle_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
print(f"loaded pickle model prediction score: {loaded_pickle_model.score(X_test, y_test)*100:.2f}%")

loaded pickle model prediction score: 78.69%


In [94]:
# loaded a saved joblib model and evaluate it
loaded_joblib_model = load("random_forest_model_1.joblib")
print(f"loaded joblib model prediction score: {loaded_joblib_model.score(X_test,y_test)*100:.2f}%")

loaded joblib model prediction score: 78.69%


In [95]:
# load a new dataset
new_data = pd.DataFrame({
    'age':[63,37,41,25],
    'sex':[1,1,0,0],
    'cp':[3,2,1,0],
    'trestbps':[145,130,130,120],
    'chol':[223,250,204,200],
    'fbs':[1,0,0,0],
    'restecg':[0,1,0,0],
    'thalach':[150,187,172,150],
    'exang':[0,0,0,0],
    'oldpeak':[2.3,3.5,1.4,2.0],
    'slope':[0,0,2,1],
    'ca':[0,0,0,0],
    'thal':[1,2,2,1]
})

In [96]:
new_data.shape

(4, 13)

In [97]:
# make prediction on the new dataset
predictions = loaded_pickle_model.predict(new_data)
predictions

array([1, 1, 1, 1], dtype=int64)

In [98]:
# alternatively make prediction on the new dataset using joblib model
prediction  = loaded_joblib_model.predict(new_data)
prediction

array([1, 1, 1, 1], dtype=int64)